title: Azimuth
baseURL: /
params:
  base_font: nunito-sans
  palette: blue
  header:
    logo_img: images/callfoundationlogo.png
    logo_img_alt: Logo
    has_nav: true
    nav_links:
      - label: Home
        url: '#'
        style: link
      - label: About Us
        url: '#about-us'
        style: link
      - url: '#what-we-do'
        style: link
        label: Our Work
      - label: Our Story
        url: /blog/our-story/
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: left
        new_window: false
        no_follow: false
        type: action
      - label: Join Us
        url: '#join-us'
        style: link
      - label: Contact Us
        style: primary
        url: '#join-us'
  domain: 'https://neat-ant-5275e.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
