title: Azimuth
baseURL: /
params:
  base_font: nunito-sans
  palette: blue
  header:
    logo_img: images/callfoundationlogo.png
    logo_img_alt: Logo
    has_nav: true
    nav_links:
      - label: Home
        url: '#'
        style: link
      - label: About Us
        url: '#about-us'
        style: link
      - url: '#what-we-do'
        style: link
        label: Our Work
      - label: Our Story
        url: /blog/our-story/
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: left
        new_window: false
        no_follow: false
        type: action
      - label: Join Us
        url: '#join-us'
        style: link
      - label: Contact Us
        style: primary
        url: '#join-us'
  footer:
    sections:
      - type: footer_text
        image: images/callfoundation.png
        image_url: /
        image_alt: Footer logo
      - type: footer_nav
        title: Company
        nav_links:
          - label: About Us
            url: /about
            style: link
          - label: Blog
            url: /blog
            style: link
          - label: Sign Up
            url: /signup
            style: link
          - label: Contact
            url: /contact
            style: link
      - type: footer_nav
        title: Community
        nav_links:
          - label: Twitter
            url: 'https://twitter.com/'
            style: link
            has_icon: true
            icon: twitter
            icon_position: left
          - label: LinkedIn
            url: 'https://www.linkedin.com/'
            style: link
            has_icon: true
            icon: linkedin
            icon_position: left
          - label: GitHub
            url: 'https://github.com/'
            style: link
            has_icon: true
            icon: github
            icon_position: left
    has_nav: true
    nav_links:
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=azimuth&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>.
  domain: 'https://neat-ant-5275e.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
