title: callfoundation
baseURL: /
params:
  title: callfoundation
  base_font: nunito-sans
  palette: blue
  header:
    logo_img: images/callfoundationlogo.png
    logo_img_alt: Logo
    has_nav: true
    nav_links:
      - label: Home
        url: '#'
        style: link
      - label: About Us
        url: '#about-us'
        style: link
      - url: '#what-we-do'
        style: link
        label: Our Work
      - label: Our Story
        url: /blog/our-story/
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: left
        new_window: false
        no_follow: false
        type: action
      - label: Join Us
        url: '#join-us'
        style: link
      - label: Contact Us
        style: primary
        url: '#join-us'
  footer:
    sections:
      - type: footer_text
        image: images/callfoundation.png
        image_url: /
        image_alt: Footer logo
      - type: footer_nav
        title: Company
        nav_links:
          - label: Home
            url: '#hero'
            style: link
            has_icon: false
            icon: arrow-left
            icon_position: left
            new_window: false
            no_follow: false
            type: action
          - label: About Us
            url: '#about-us'
            style: link
          - label: Our Work
            url: '#what-we-do'
            style: link
          - label: Our team
            url: '#our-team'
            style: link
            has_icon: false
            icon: arrow-left
            icon_position: left
            new_window: false
            no_follow: false
            type: action
          - label: Our Story
            url: /blog/our-story/
            style: link
          - label: Join Us
            url: '#join-us'
            style: link
      - type: footer_nav
        title: Community
        nav_links:
          - label: Twitter
            url: 'https://twitter.com/'
            style: link
            has_icon: true
            icon: twitter
            icon_position: left
          - label: Instagram
            url: 'https://www.linkedin.com/'
            style: link
            has_icon: true
            icon: instagram
            icon_position: left
      - image_alt: lorem-ipsum
        image_url: lorem-ipsum
        title: Email us at
        content: |
          contact@callfoundation.co.in
        type: footer_text
    has_nav: true
    nav_links: []
    content: null
  domain: 'https://neat-ant-5275e.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
